# Generated by Django 5.1.7 on 2025-05-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('holder_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('APL', 'Above Poverty Line'), ('BPL', 'Below Poverty Line'), ('AAY', 'Antyodaya Anna Yojana')], max_length=3)),
                ('address', models.TextField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ration_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='beneficiary_management.rationcard')),
            ],
        ),
    ]
